// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCsQW2YZ98J3uOxumSYONg3VfmAtAkA_8',
    appId: '1:469664748258:web:519f1b8e8a9d8d485684bb',
    messagingSenderId: '469664748258',
    projectId: 'ci-cd-97cbb',
    authDomain: 'ci-cd-97cbb.firebaseapp.com',
    storageBucket: 'ci-cd-97cbb.firebasestorage.app',
    measurementId: 'G-LY5VL0KDE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Mxq24io6a-5vOyV51iOlNM3yv_HOkg8',
    appId: '1:469664748258:android:f4029842d3762afc5684bb',
    messagingSenderId: '469664748258',
    projectId: 'ci-cd-97cbb',
    storageBucket: 'ci-cd-97cbb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCsQW2YZ98J3uOxumSYONg3VfmAtAkA_8',
    appId: '1:469664748258:web:b89c4fd04bfb8b685684bb',
    messagingSenderId: '469664748258',
    projectId: 'ci-cd-97cbb',
    authDomain: 'ci-cd-97cbb.firebaseapp.com',
    storageBucket: 'ci-cd-97cbb.firebasestorage.app',
    measurementId: 'G-3PE448MLFB',
  );
}
